# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 14:26
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='project.ProjectCategory'),
        ),
    ]
