# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_projectpage_cateogry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='cateogry',
        ),
    ]
