# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_projectpage_cateogry'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='category',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
