# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_projectpage_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='categories',
        ),
        migrations.DeleteModel(
            name='ProjectCategory',
        ),
    ]
