# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-28 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_projectindexpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='tags',
        ),
    ]
