# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-28 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_remove_projectpage_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpagetag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='projectpagetag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='category',
        ),
        migrations.DeleteModel(
            name='ProjectPageTag',
        ),
    ]
