# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_projectpageprojectslideshowimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='teaser_intro',
            field=models.TextField(blank=True, help_text='This text will appear below teaser'),
        ),
    ]
