# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_projectpage_teaser_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='teaser_intro',
            field=models.TextField(blank=True, help_text='This text will appear below teaser', max_length='140'),
        ),
    ]
