# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20180105_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpageprojectslideshowimages',
            name='slide_description',
            field=models.TextField(blank=True),
        ),
    ]
