# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-05 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_projectcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategoryPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='project.ProjectCategory')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='project.ProjectPage')),
            ],
            options={
                'verbose_name': 'Project category placement',
                'verbose_name_plural': 'Project category placements',
            },
        ),
    ]
