# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-05 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_projectcategoryplacement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcategoryplacement',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='projectcategoryplacement',
            name='page',
        ),
        migrations.DeleteModel(
            name='ProjectCategory',
        ),
        migrations.DeleteModel(
            name='ProjectCategoryPlacement',
        ),
    ]
