# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-05 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_auto_20180505_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='teaser_intro',
            field=models.TextField(blank=True, help_text='This text will appear below teaser', max_length='540'),
        ),
    ]
