# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-05 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_auto_20180505_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='show_on_front',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
