# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-05 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_projectpage_show_on_front'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='show_on_front',
            field=models.BooleanField(help_text='Select if this content is listed on the front page'),
        ),
    ]
