# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-05 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('standardpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image'),
        ),
    ]
